### ISSUE TITLE
NameError: global name 'urllib2' is not defined

### ISSUE THREAD

**Issue by beettlefor** [susmithHCK/torghost#1]
i have this msg

Traceback (most recent call last):
  File "/usr/bin/torghost", line 164, in <module>
    start_torghost()
  File "/usr/bin/torghost", line 135, in start_torghost
    print t()+" CURRENT IP : "+bcolors.GREEN+ip()+bcolors.ENDC
  File "/usr/bin/torghost", line 65, in ip
    except urllib2.URLError:

...but its run good.

**Comment by sipycup** [comment]
I have the same issue which causes everything to crash and not work

**Comment by susmithHCK** [comment]
Sorry for the late response, the bug is now fixed. thank you
