### ISSUE TITLE
When I try to run torghost ImportError: No module named stem 

### ISSUE THREAD

**Issue by ScumHum** [susmithHCK/torghost#26]
when I try to run `Pip install stem`

`Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
`

**Comment by akrolla** [comment]
akrolla@kali:~/Desktop/stuff/tools/torghost$ sudo pip install stem
Requirement already satisfied: stem in /usr/local/lib/python3.6/dist-packages
akrolla@kali:~/Desktop/stuff/tools/torghost$ sudo pip3 install stem
Requirement already satisfied: stem in /usr/local/lib/python3.6/dist-packages
akrolla@kali:~/Desktop/stuff/tools/torghost$ ./install.sh
******* Torghost installer ********

=====> Installing tor bundle 
=====> Installing dependencies 
Requirement already satisfied: stem in /usr/local/lib/python3.6/dist-packages
=====> Installing TorGhost 
=====> Done 
=====> Open terminal and type 'torghost' for usage 
akrolla@kali:~/Desktop/stuff/tools/torghost$ torghost
Traceback (most recent call last):
  File "/usr/bin/torghost", line 9, in <module>
    from stem import Signal
ImportError: No module named stem

**Comment by susmithHCK** [comment]
Torghost is for python 2.7 not python 3. 
Try installing "pip2 install stem"

**Comment by qasem5252** [comment]
I start torghost and I can't connect to the internet
